# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeavePortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
