# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeavePortal', '0002_auto_20191231_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(),
        ),
    ]
